In [1]:
import pandas as pd

In [2]:
locacao = pd.read_json('/content/dados_locacao_imoveis.json')
locacao.head()

                                       dados_locacao
0  {'apartamento': 'A101 (blocoAP)', 'datas_combi...
1  {'apartamento': 'A102 (blocoAP)', 'datas_combi...
2  {'apartamento': 'B201 (blocoAP)', 'datas_combi...
3  {'apartamento': 'B202 (blocoAP)', 'datas_combi...
4  {'apartamento': 'C301 (blocoAP)', 'datas_combi...

In [3]:
locacao = pd.json_normalize(locacao['dados_locacao'])

In [4]:
locacao

,apartamento,datas_combinadas_pagamento,datas_de_pagamento,valor_aluguel
0,A101 (blocoAP),"[01/06/2022, 01/07/2022]","[05/06/2022, 03/07/2022]","[$ 1000,0 reais, $ 2500,0 reais]"
1,A102 (blocoAP),"[02/06/2022, 02/07/2022]","[02/06/2022, 06/07/2022]","[$ 1100,0 reais, $ 2600,0 reais]"
2,B201 (blocoAP),"[03/06/2022, 03/07/2022]","[07/06/2022, 03/07/2022]","[$ 1200,0 reais, $ 2700,0 reais]"
3,B202 (blocoAP),"[04/06/2022, 04/07/2022]","[07/06/2022, 05/07/2022]","[$ 1300,0 reais, $ 2800,0 reais]"
4,C301 (blocoAP),"[05/06/2022, 05/07/2022]","[10/06/2022, 09/07/2022]","[$ 1400,0 reais, $ 2900,0 reais]"
5,C302 (blocoAP),"[06/06/2022, 06/07/2022]","[08/06/2022, 12/07/2022]","[$ 1500,0 reais, $ 1200,0 reais]"
6,D401 (blocoAP),"[07/06/2022, 07/07/2022]","[07/06/2022, 09/07/2022]","[$ 1600,0 reais, $ 1300,0 reais]"
7,D402 (blocoAP),"[08/06/2022, 08/07/2022]","[10/06/2022, 14/07/2022]","[$ 1700,0 reais, $ 1400,0 reais]"
8,E501 (blocoAP),"[09/06/2022, 09/07/2022]","[10/06/2022, 09/07/2022]","[$ 1800,0 reais, $ 1500,0 reais]"
9,E502 (blocoAP),"[10/06/2022, 10/07/2022]","[16/06/2022, 12/07/2022]","[$ 1900,0 reais, $ 1600,0 reais]"
10,F601 (blocoAP),"[11/06/2022, 11/07/2022]","[17/06/2022, 13/07/2022]","[$ 2000,0 reais, $ 1000,0 reais]"
11,F602 (blocoAP),"[12/06/2022, 12/07/2022]","[15/06/2022, 12/07/2022]","[$ 2100,0 reais, $ 1100,0 reais]"
12,G701 (blocoAP),"[13/06/2022, 13/07/2022]","[19/06/2022, 20/07/2022]","[$ 2200,0 reais, $ 1200,0 reais]"
13,G702 (blocoAP),"[14/06/2022, 14/07/2022]","[15/06/2022, 17/07/2022]","[$ 2300,0 reais, $ 2100,0 reais]"
14,H801 (blocoAP),"[15/06/2022, 15/07/2022]","[18/06/2022, 16/07/2022]","[$ 2400,0 reais, $ 2200,0 reais]"

In [5]:
vendas = pd.read_json('/content/dados_vendas_clientes.json')
vendas.head()

                                        dados_vendas
0  {'Data de venda': '06/06/2022', 'Cliente': ['@...
1  {'Data de venda': '07/06/2022', 'Cliente': ['I...
2  {'Data de venda': '08/06/2022', 'Cliente': ['I...
3  {'Data de venda': '09/06/2022', 'Cliente': ['J...
4  {'Data de venda': '10/06/2022', 'Cliente': ['M...

In [6]:
vendas = pd.json_normalize(vendas['dados_vendas'])

In [7]:
vendas

,Data de venda,Cliente,Valor da compra
0,06/06/2022,"[@ANA _LUCIA 321, DieGO ARMANDIU 210, DieGO AR...","[R$ 836,5, R$ 573,33, R$ 392,8, R$ 512,34]"
1,07/06/2022,"[Isabely JOanes 738, Isabely JOanes 738, Isabe...","[R$ 825,31, R$ 168,07, R$ 339,18, R$ 314,69]"
2,08/06/2022,"[Isabely JOanes 738, JOãO Gabriel 671, Julya m...","[R$ 682,05, R$ 386,34, R$ 622,65, R$ 630,79]"
3,09/06/2022,"[Julya meireles 914, MaRIA Julia 444, MaRIA Ju...","[R$ 390,3, R$ 759,16, R$ 334,47, R$ 678,78]"
4,10/06/2022,"[MaRIA Julia 444, PEDRO PASCO 812, Paulo castr...","[R$ 314,24, R$ 311,15, R$ 899,16, R$ 885,24]"

Voltemos a pôr em prática tudo o que aprendemos durante as aulas. Disponibilizei novamente os 2 novos conjuntos de dados para download abaixo:

Projeto desafio 1: vendas online - dados_vendas_clientes.json;
Projeto desafio 2: administração de condomínios - dados_locacao_imoveis.json.
Lembrando: São dois projetos de tratamento que serão construídos durante o andamento do curso. Portanto, salve seu código de construção em cada desafio para que possa aplicá-lo nos desafios posteriores.

Etapa 2
Projeto desafio 1: vendas online
Lemos a base de dados no desafio anterior, agora podemos avançar nas transformações desses dados. Então, o novo desafio do projeto 1 será dividido em algumas metas:

Remover os dados em listas dentro do DataFrame;

In [8]:
vendas.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Data de venda    5 non-null      object
 1   Cliente          5 non-null      object
 2   Valor da compra  5 non-null      object
dtypes: object(3)
memory usage: 252.0+ bytes

*   Remover os dados em listas dentro do DataFrame;

In [9]:
colunas = list(vendas.columns)

In [10]:
vendas = vendas.explode(colunas[1:])

In [11]:
vendas

  Data de venda             Cliente Valor da compra
0    06/06/2022     @ANA _LUCIA 321        R$ 836,5
0    06/06/2022  DieGO ARMANDIU 210       R$ 573,33
0    06/06/2022  DieGO ARMANDIU 210        R$ 392,8
0    06/06/2022  DieGO ARMANDIU 210       R$ 512,34
1    07/06/2022  Isabely JOanes 738       R$ 825,31
1    07/06/2022  Isabely JOanes 738       R$ 168,07
1    07/06/2022  Isabely JOanes 738       R$ 339,18
1    07/06/2022  Isabely JOanes 738       R$ 314,69
2    08/06/2022  Isabely JOanes 738       R$ 682,05
2    08/06/2022    JOãO Gabriel 671       R$ 386,34
2    08/06/2022  Julya meireles 914       R$ 622,65
2    08/06/2022  Julya meireles 914       R$ 630,79
3    09/06/2022  Julya meireles 914        R$ 390,3
3    09/06/2022     MaRIA Julia 444       R$ 759,16
3    09/06/2022     MaRIA Julia 444       R$ 334,47
3    09/06/2022     MaRIA Julia 444       R$ 678,78
4    10/06/2022     MaRIA Julia 444       R$ 314,24
4    10/06/2022     PEDRO PASCO 812       R$ 311,15
4    10/06/2022    Paulo castro 481       R$ 899,16
4    10/06/2022   Thiago fritzz 883       R$ 885,24

*   Verificar os tipos de dados;

In [12]:
vendas.info()

<class 'pandas.core.frame.DataFrame'>
Index: 20 entries, 0 to 4
Data columns (total 3 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Data de venda    20 non-null     object
 1   Cliente          20 non-null     object
 2   Valor da compra  20 non-null     object
dtypes: object(3)
memory usage: 1.2+ KB

*   Identificar colunas numéricas;

In [13]:
vendas['Valor da compra']

0     R$ 836,5
0    R$ 573,33
0     R$ 392,8
0    R$ 512,34
1    R$ 825,31
1    R$ 168,07
1    R$ 339,18
1    R$ 314,69
2    R$ 682,05
2    R$ 386,34
2    R$ 622,65
2    R$ 630,79
3     R$ 390,3
3    R$ 759,16
3    R$ 334,47
3    R$ 678,78
4    R$ 314,24
4    R$ 311,15
4    R$ 899,16
4    R$ 885,24
Name: Valor da compra, dtype: object

*   Transformar a coluna numérica para o tipo numérico.

In [14]:
import numpy as np

In [15]:
vendas['Valor da compra'] = vendas['Valor da compra'].apply(lambda x: x.replace('$','').replace(',','').replace('R','').strip())

In [16]:
vendas['Valor da compra'] = vendas['Valor da compra'].astype(float)

Projeto desafio 2: administração de condomínios
Lemos a base de dados no desafio anterior, agora podemos avançar nas transformações desses dados. Então, da mesma forma que o projeto 1, o desafio do projeto 2 está listado em algumas metas:

Remover os dados em listas dentro do DataFrame;
Verificar os tipos de dados;
Identificar colunas numéricas;
Transformar a coluna numérica para o tipo numérico.

In [17]:
locacao

,apartamento,datas_combinadas_pagamento,datas_de_pagamento,valor_aluguel
0,A101 (blocoAP),"[01/06/2022, 01/07/2022]","[05/06/2022, 03/07/2022]","[$ 1000,0 reais, $ 2500,0 reais]"
1,A102 (blocoAP),"[02/06/2022, 02/07/2022]","[02/06/2022, 06/07/2022]","[$ 1100,0 reais, $ 2600,0 reais]"
2,B201 (blocoAP),"[03/06/2022, 03/07/2022]","[07/06/2022, 03/07/2022]","[$ 1200,0 reais, $ 2700,0 reais]"
3,B202 (blocoAP),"[04/06/2022, 04/07/2022]","[07/06/2022, 05/07/2022]","[$ 1300,0 reais, $ 2800,0 reais]"
4,C301 (blocoAP),"[05/06/2022, 05/07/2022]","[10/06/2022, 09/07/2022]","[$ 1400,0 reais, $ 2900,0 reais]"
5,C302 (blocoAP),"[06/06/2022, 06/07/2022]","[08/06/2022, 12/07/2022]","[$ 1500,0 reais, $ 1200,0 reais]"
6,D401 (blocoAP),"[07/06/2022, 07/07/2022]","[07/06/2022, 09/07/2022]","[$ 1600,0 reais, $ 1300,0 reais]"
7,D402 (blocoAP),"[08/06/2022, 08/07/2022]","[10/06/2022, 14/07/2022]","[$ 1700,0 reais, $ 1400,0 reais]"
8,E501 (blocoAP),"[09/06/2022, 09/07/2022]","[10/06/2022, 09/07/2022]","[$ 1800,0 reais, $ 1500,0 reais]"
9,E502 (blocoAP),"[10/06/2022, 10/07/2022]","[16/06/2022, 12/07/2022]","[$ 1900,0 reais, $ 1600,0 reais]"
10,F601 (blocoAP),"[11/06/2022, 11/07/2022]","[17/06/2022, 13/07/2022]","[$ 2000,0 reais, $ 1000,0 reais]"
11,F602 (blocoAP),"[12/06/2022, 12/07/2022]","[15/06/2022, 12/07/2022]","[$ 2100,0 reais, $ 1100,0 reais]"
12,G701 (blocoAP),"[13/06/2022, 13/07/2022]","[19/06/2022, 20/07/2022]","[$ 2200,0 reais, $ 1200,0 reais]"
13,G702 (blocoAP),"[14/06/2022, 14/07/2022]","[15/06/2022, 17/07/2022]","[$ 2300,0 reais, $ 2100,0 reais]"
14,H801 (blocoAP),"[15/06/2022, 15/07/2022]","[18/06/2022, 16/07/2022]","[$ 2400,0 reais, $ 2200,0 reais]"

In [18]:
colunas = list(locacao.columns)

In [19]:
colunas

['apartamento',
 'datas_combinadas_pagamento',
 'datas_de_pagamento',
 'valor_aluguel']

In [20]:
locacao = locacao.explode(colunas[1:])

In [21]:
locacao

,apartamento,datas_combinadas_pagamento,datas_de_pagamento,valor_aluguel
0,A101 (blocoAP),01/06/2022,05/06/2022,"$ 1000,0 reais"
0,A101 (blocoAP),01/07/2022,03/07/2022,"$ 2500,0 reais"
1,A102 (blocoAP),02/06/2022,02/06/2022,"$ 1100,0 reais"
1,A102 (blocoAP),02/07/2022,06/07/2022,"$ 2600,0 reais"
2,B201 (blocoAP),03/06/2022,07/06/2022,"$ 1200,0 reais"
2,B201 (blocoAP),03/07/2022,03/07/2022,"$ 2700,0 reais"
3,B202 (blocoAP),04/06/2022,07/06/2022,"$ 1300,0 reais"
3,B202 (blocoAP),04/07/2022,05/07/2022,"$ 2800,0 reais"
4,C301 (blocoAP),05/06/2022,10/06/2022,"$ 1400,0 reais"
4,C301 (blocoAP),05/07/2022,09/07/2022,"$ 2900,0 reais"
5,C302 (blocoAP),06/06/2022,08/06/2022,"$ 1500,0 reais"
5,C302 (blocoAP),06/07/2022,12/07/2022,"$ 1200,0 reais"
6,D401 (blocoAP),07/06/2022,07/06/2022,"$ 1600,0 reais"
6,D401 (blocoAP),07/07/2022,09/07/2022,"$ 1300,0 reais"
7,D402 (blocoAP),08/06/2022,10/06/2022,"$ 1700,0 reais"
7,D402 (blocoAP),08/07/2022,14/07/2022,"$ 1400,0 reais"
8,E501 (blocoAP),09/06/2022,10/06/2022,"$ 1800,0 reais"
8,E501 (blocoAP),09/07/2022,09/07/2022,"$ 1500,0 reais"
9,E502 (blocoAP),10/06/2022,16/06/2022,"$ 1900,0 reais"
9,E502 (blocoAP),10/07/2022,12/07/2022,"$ 1600,0 reais"
10,F601 (blocoAP),11/06/2022,17/06/2022,"$ 2000,0 reais"
10,F601 (blocoAP),11/07/2022,13/07/2022,"$ 1000,0 reais"
11,F602 (blocoAP),12/06/2022,15/06/2022,"$ 2100,0 reais"
11,F602 (blocoAP),12/07/2022,12/07/2022,"$ 1100,0 reais"
12,G701 (blocoAP),13/06/2022,19/06/2022,"$ 2200,0 reais"
12,G701 (blocoAP),13/07/2022,20/07/2022,"$ 1200,0 reais"
13,G702 (blocoAP),14/06/2022,15/06/2022,"$ 2300,0 reais"
13,G702 (blocoAP),14/07/2022,17/07/2022,"$ 2100,0 reais"
14,H801 (blocoAP),15/06/2022,18/06/2022,"$ 2400,0 reais"
14,H801 (blocoAP),15/07/2022,16/07/2022,"$ 2200,0 reais"

In [22]:
locacao.info()

<class 'pandas.core.frame.DataFrame'>
Index: 30 entries, 0 to 14
Data columns (total 4 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   apartamento                 30 non-null     object
 1   datas_combinadas_pagamento  30 non-null     object
 2   datas_de_pagamento          30 non-null     object
 3   valor_aluguel               30 non-null     object
dtypes: object(4)
memory usage: 1.2+ KB

In [23]:
locacao['valor_aluguel']

0     $ 1000,0 reais
0     $ 2500,0 reais
1     $ 1100,0 reais
1     $ 2600,0 reais
2     $ 1200,0 reais
2     $ 2700,0 reais
3     $ 1300,0 reais
3     $ 2800,0 reais
4     $ 1400,0 reais
4     $ 2900,0 reais
5     $ 1500,0 reais
5     $ 1200,0 reais
6     $ 1600,0 reais
6     $ 1300,0 reais
7     $ 1700,0 reais
7     $ 1400,0 reais
8     $ 1800,0 reais
8     $ 1500,0 reais
9     $ 1900,0 reais
9     $ 1600,0 reais
10    $ 2000,0 reais
10    $ 1000,0 reais
11    $ 2100,0 reais
11    $ 1100,0 reais
12    $ 2200,0 reais
12    $ 1200,0 reais
13    $ 2300,0 reais
13    $ 2100,0 reais
14    $ 2400,0 reais
14    $ 2200,0 reais
Name: valor_aluguel, dtype: object

In [24]:
locacao['valor_aluguel'] = locacao['valor_aluguel'].apply(lambda x: x.replace('$','').replace(',','.').replace('reais','').strip())

In [27]:
locacao

,apartamento,datas_combinadas_pagamento,datas_de_pagamento,valor_aluguel
0,A101 (blocoAP),01/06/2022,05/06/2022,1000.0
0,A101 (blocoAP),01/07/2022,03/07/2022,2500.0
1,A102 (blocoAP),02/06/2022,02/06/2022,1100.0
1,A102 (blocoAP),02/07/2022,06/07/2022,2600.0
2,B201 (blocoAP),03/06/2022,07/06/2022,1200.0
2,B201 (blocoAP),03/07/2022,03/07/2022,2700.0
3,B202 (blocoAP),04/06/2022,07/06/2022,1300.0
3,B202 (blocoAP),04/07/2022,05/07/2022,2800.0
4,C301 (blocoAP),05/06/2022,10/06/2022,1400.0
4,C301 (blocoAP),05/07/2022,09/07/2022,2900.0
5,C302 (blocoAP),06/06/2022,08/06/2022,1500.0
5,C302 (blocoAP),06/07/2022,12/07/2022,1200.0
6,D401 (blocoAP),07/06/2022,07/06/2022,1600.0
6,D401 (blocoAP),07/07/2022,09/07/2022,1300.0
7,D402 (blocoAP),08/06/2022,10/06/2022,1700.0
7,D402 (blocoAP),08/07/2022,14/07/2022,1400.0
8,E501 (blocoAP),09/06/2022,10/06/2022,1800.0
8,E501 (blocoAP),09/07/2022,09/07/2022,1500.0
9,E502 (blocoAP),10/06/2022,16/06/2022,1900.0
9,E502 (blocoAP),10/07/2022,12/07/2022,1600.0
10,F601 (blocoAP),11/06/2022,17/06/2022,2000.0
10,F601 (blocoAP),11/07/2022,13/07/2022,1000.0
11,F602 (blocoAP),12/06/2022,15/06/2022,2100.0
11,F602 (blocoAP),12/07/2022,12/07/2022,1100.0
12,G701 (blocoAP),13/06/2022,19/06/2022,2200.0
12,G701 (blocoAP),13/07/2022,20/07/2022,1200.0
13,G702 (blocoAP),14/06/2022,15/06/2022,2300.0
13,G702 (blocoAP),14/07/2022,17/07/2022,2100.0
14,H801 (blocoAP),15/06/2022,18/06/2022,2400.0
14,H801 (blocoAP),15/07/2022,16/07/2022,2200.0

In [26]:
locacao['valor_aluguel'] = locacao['valor_aluguel'].astype(np.float64)

Voltemos a pôr em prática tudo o que aprendemos durante as aulas. Disponibilizei novamente os 2 novos conjuntos de dados para download abaixo:

Projeto desafio 1: vendas online - dados_vendas_clientes.json;
Projeto desafio 2: administração de condomínios - dados_locacao_imoveis.json.
Lembrando: São dois projetos de tratamento que serão construídos durante o andamento do curso. Portanto, salve seu código de construção em cada desafio para que possa aplicá-lo nos desafios posteriores.

#Etapa 3
##Projeto desafio 1: vendas online

Na etapa 2, trabalhamos na transformação dos dados numéricos. Agora, podemos trabalhar com valores textuais.

Devido a uma instabilidade no site da empresa, tivemos problemas com os nomes dos clientes durante o salvamento. Isso resultou em uma coluna de nomes de clientes com uma mistura de letras, maiúsculas e minúsculas, números e outros caracteres.

**Sabendo disso, manipule os textos presentes na coluna Cliente para que seja obtido como resultado os nomes dos clientes em letras minúsculas, com a ausência de caracteres especiais ou números.**

In [28]:
vendas

  Data de venda             Cliente  Valor da compra
0    06/06/2022     @ANA _LUCIA 321           8365.0
0    06/06/2022  DieGO ARMANDIU 210          57333.0
0    06/06/2022  DieGO ARMANDIU 210           3928.0
0    06/06/2022  DieGO ARMANDIU 210          51234.0
1    07/06/2022  Isabely JOanes 738          82531.0
1    07/06/2022  Isabely JOanes 738          16807.0
1    07/06/2022  Isabely JOanes 738          33918.0
1    07/06/2022  Isabely JOanes 738          31469.0
2    08/06/2022  Isabely JOanes 738          68205.0
2    08/06/2022    JOãO Gabriel 671          38634.0
2    08/06/2022  Julya meireles 914          62265.0
2    08/06/2022  Julya meireles 914          63079.0
3    09/06/2022  Julya meireles 914           3903.0
3    09/06/2022     MaRIA Julia 444          75916.0
3    09/06/2022     MaRIA Julia 444          33447.0
3    09/06/2022     MaRIA Julia 444          67878.0
4    10/06/2022     MaRIA Julia 444          31424.0
4    10/06/2022     PEDRO PASCO 812          31115.0
4    10/06/2022    Paulo castro 481          89916.0
4    10/06/2022   Thiago fritzz 883          88524.0

In [47]:
vendas['Cliente'] = vendas['Cliente'].replace('[^a-zA-Z\-\']', ' ',regex=True)

<>:1: SyntaxWarning: invalid escape sequence '\-'
<>:1: SyntaxWarning: invalid escape sequence '\-'
/tmp/ipykernel_27151/3436296911.py:1: SyntaxWarning: invalid escape sequence '\-'
  vendas['Cliente'] = vendas['Cliente'].replace('[^a-zA-Z\-\']', ' ',regex=True).strip()

AttributeError: 'Series' object has no attribute 'strip'

In [48]:
vendas['Cliente'] = vendas['Cliente'].str.lower()

In [42]:
vendas.head()

  Data de venda             Cliente  Valor da compra
0    06/06/2022      ana  lucia               8365.0
0    06/06/2022  diego armandiu              57333.0
0    06/06/2022  diego armandiu               3928.0
0    06/06/2022  diego armandiu              51234.0
1    07/06/2022  isabely joanes              82531.0

#Projeto desafio 2: administração de condomínios
##Na etapa 2, trabalhamos na transformação dos dados numéricos. Agora, podemos trabalhar com valores textuais.

##Buscando explicar a organização da identificação dos apartamentos, durante a criação do conjunto de dados, foi adicionado o texto (blocoAP). Esse texto informa que os nomes dos apartamentos estão organizados com a letra do bloco seguida do número do apartamento. No entanto, isso não traz nenhuma informação para nossos dados, sendo interessante realizar a remoção desse texto no conjunto de dados.

##**Com isso, manipule os textos na coluna apartamento para remover o texto (blocoAP) do DataFrame.**

In [43]:
locacao

,apartamento,datas_combinadas_pagamento,datas_de_pagamento,valor_aluguel
0,A101 (blocoAP),01/06/2022,05/06/2022,1000.0
0,A101 (blocoAP),01/07/2022,03/07/2022,2500.0
1,A102 (blocoAP),02/06/2022,02/06/2022,1100.0
1,A102 (blocoAP),02/07/2022,06/07/2022,2600.0
2,B201 (blocoAP),03/06/2022,07/06/2022,1200.0
2,B201 (blocoAP),03/07/2022,03/07/2022,2700.0
3,B202 (blocoAP),04/06/2022,07/06/2022,1300.0
3,B202 (blocoAP),04/07/2022,05/07/2022,2800.0
4,C301 (blocoAP),05/06/2022,10/06/2022,1400.0
4,C301 (blocoAP),05/07/2022,09/07/2022,2900.0
5,C302 (blocoAP),06/06/2022,08/06/2022,1500.0
5,C302 (blocoAP),06/07/2022,12/07/2022,1200.0
6,D401 (blocoAP),07/06/2022,07/06/2022,1600.0
6,D401 (blocoAP),07/07/2022,09/07/2022,1300.0
7,D402 (blocoAP),08/06/2022,10/06/2022,1700.0
7,D402 (blocoAP),08/07/2022,14/07/2022,1400.0
8,E501 (blocoAP),09/06/2022,10/06/2022,1800.0
8,E501 (blocoAP),09/07/2022,09/07/2022,1500.0
9,E502 (blocoAP),10/06/2022,16/06/2022,1900.0
9,E502 (blocoAP),10/07/2022,12/07/2022,1600.0
10,F601 (blocoAP),11/06/2022,17/06/2022,2000.0
10,F601 (blocoAP),11/07/2022,13/07/2022,1000.0
11,F602 (blocoAP),12/06/2022,15/06/2022,2100.0
11,F602 (blocoAP),12/07/2022,12/07/2022,1100.0
12,G701 (blocoAP),13/06/2022,19/06/2022,2200.0
12,G701 (blocoAP),13/07/2022,20/07/2022,1200.0
13,G702 (blocoAP),14/06/2022,15/06/2022,2300.0
13,G702 (blocoAP),14/07/2022,17/07/2022,2100.0
14,H801 (blocoAP),15/06/2022,18/06/2022,2400.0
14,H801 (blocoAP),15/07/2022,16/07/2022,2200.0

In [46]:
locacao['apartamento'] = locacao['apartamento'].str.replace('(blocoAP)','')

In [49]:
locacao.head()

  apartamento datas_combinadas_pagamento datas_de_pagamento  valor_aluguel
0       A101                  01/06/2022         05/06/2022         1000.0
0       A101                  01/07/2022         03/07/2022         2500.0
1       A102                  02/06/2022         02/06/2022         1100.0
1       A102                  02/07/2022         06/07/2022         2600.0
2       B201                  03/06/2022         07/06/2022         1200.0