In [1]:
import json

with open('informacoes.json') as f:
    dados = json.load(f)

In [2]:
import pandas as pd

informacoes = pd.json_normalize(dados, record_path='enderecos', meta=['nome', 'idade'])

In [3]:
informacoes

       tipo    rua  numero          cidade  nome idade
0      casa  Rua A     123       São Paulo  João    28
1  trabalho  Rua B     456  Rio de Janeiro  João    28

In [11]:
import json

with open('dados.json', 'r') as f:
    dados = json.load(f)

In [12]:
import pandas as pd

df = pd.json_normalize(dados, record_path=['pessoas'])

In [14]:
df

,nome,idade,telefones,endereco.rua,endereco.numero,endereco.cidade
0,João,25,"[11 1111-1111, 11 2222-2222]",Rua A,123,São Paulo
1,Maria,30,[21 3333-3333],,456,Rio de Janeiro

In [15]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2 entries, 0 to 1
Data columns (total 6 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   nome             2 non-null      object
 1   idade            2 non-null      object
 2   telefones        2 non-null      object
 3   endereco.rua     2 non-null      object
 4   endereco.numero  2 non-null      int64
 5   endereco.cidade  2 non-null      object
dtypes: int64(1), object(5)
memory usage: 228.0+ bytes

In [16]:
df['idade'] = df['idade'].astype(int)

In [17]:
df_filtrado = df.query('`endereco.rua` != ""')

In [18]:
df_filtrado = df[df['endereco.rua'] != ""]

In [19]:
df_filtrado

,nome,idade,telefones,endereco.rua,endereco.numero,endereco.cidade
0,João,25,"[11 1111-1111, 11 2222-2222]",Rua A,123,São Paulo